server.port=8080

spring.datasource.url=jdbc:postgresql://db.yffsnzzzavqpstywkhgx.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Hlawutelo@144
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.web.cors.allowed-origins=*
spring.application.name=HireFlow

jwt.secret=HireFlow_JWT_Secret_Key_2024_SuperSecureKey_ChangeInProduction
jwt.expiration=86400000
